name: advent_cli
description: A command-line application for managing & participating in Advent Of Code.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
