name: advent_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  cli_config: ^0.2.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  http: ^1.2.2
  lints: ^5.0.0
  test: ^1.24.0
